"""
Outline conversion for the canonical Zyro glyph (v2.5).
Carves the white Orbit centerline (stroke width 9) out of the black field,
producing ONE black compound polygon with the Orbit as counters (holes).

Pure-Python (shapely). Reproducible. Source of truth = canonical path data below.
Run: python zyro_outline.py  ->  writes ../dist/zyro-glyph-outline.svg
"""
from pathlib import Path
from shapely.geometry import Polygon, LineString

BASE = Path(__file__).resolve().parent.parent   # ZYRO/GLYPH
DIST = BASE / "dist"
DIST.mkdir(exist_ok=True)

# ----- canonical path data (mirrors zyro-glyph-canonical.svg) -----
ORBIT = [
    (47, 51),
    [(52, 48), (55, 52), (54, 57)],
    [(52, 65), (41, 68), (34, 62)],
    [(24, 54), (27, 39), (38, 33)],
    [(53, 24), (70, 34), (72, 50)],
    [(74, 68), (59, 80), (43, 80)],
    [(23, 80), (12, 66), (12, 49)],
    [(12, 30), (27, 16), (46, 16)],
    [(65, 16), (79, 28), (93, 42)],
    [(96, 45), (98, 48), (100, 50)],
    [(115, 34), (132, 16), (153, 16)],
    [(173, 16), (187, 31), (187, 50)],
    [(187, 69), (173, 84), (153, 84)],
    [(133, 84), (116, 66), (100, 50)],
    [(97, 53), (94, 56), (91, 59)],
    [(82, 68), (75, 75), (66, 79)],
]
FIELD = [
    (100, 35),
    [(84, 22), (67, 9), (45, 8)],
    [(20, 7), (5, 25), (5, 50)],
    [(5, 76), (23, 93), (49, 93)],
    [(70, 93), (85, 81), (100, 67)],
    [(115, 81), (131, 93), (153, 93)],
    [(178, 93), (195, 75), (195, 50)],
    [(195, 25), (178, 7), (153, 7)],
    [(131, 7), (115, 20), (100, 33)],
    [(99, 34), (99, 34), (100, 35)],
]

STROKE_W = 9.0
SAMPLES = 48  # per cubic segment


def cubic(p0, p1, p2, p3, n):
    out = []
    for i in range(1, n + 1):
        t = i / n
        mt = 1 - t
        out.append((mt**3*p0[0] + 3*mt**2*t*p1[0] + 3*mt*t**2*p2[0] + t**3*p3[0],
                    mt**3*p0[1] + 3*mt**2*t*p1[1] + 3*mt*t**2*p2[1] + t**3*p3[1]))
    return out


def flatten(path, n):
    pts = [path[0]]
    cur = path[0]
    for p1, p2, p3 in path[1:]:
        pts.extend(cubic(cur, p1, p2, p3, n))
        cur = p3
    return pts


def build():
    field_poly = Polygon(flatten(FIELD, SAMPLES)).buffer(0)
    channel = LineString(flatten(ORBIT, SAMPLES)).buffer(
        STROKE_W / 2.0, cap_style="round", join_style="round")
    glyph = field_poly.difference(channel).buffer(0)
    return glyph


def ring_d(coords):
    return "M " + " L ".join(f"{x:.2f} {y:.2f}" for x, y in coords) + " Z"


def main():
    glyph = build()
    polys = list(glyph.geoms) if glyph.geom_type == "MultiPolygon" else [glyph]
    nholes = sum(len(p.interiors) for p in polys)
    print(f"geom={glyph.geom_type} parts={len(polys)} holes={nholes} "
          f"area={glyph.area:.1f} valid={glyph.is_valid}")

    subpaths = []
    for p in polys:
        subpaths.append(ring_d(p.exterior.coords))
        for hole in p.interiors:
            subpaths.append(ring_d(hole.coords))
    d = " ".join(subpaths)

    svg = ('<?xml version="1.0" encoding="UTF-8"?>\n'
           '<!-- Zyro Glyph outline (fill-only, Orbit as counters). Generated by build/zyro_outline.py -->\n'
           '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 200 100" width="200" height="100"\n'
           '     data-zyro-canonical="true" data-stage="outline" role="img" aria-label="Zyro glyph outline">\n'
           f'  <path fill="#000000" fill-rule="evenodd" d="{d}"/>\n'
           '</svg>\n')
    out = DIST / "zyro-glyph-outline.svg"
    out.write_text(svg, encoding="utf-8")
    print("wrote", out)
    return glyph


if __name__ == "__main__":
    main()
